# Secret para armazenar as credenciais do PostgreSQL de forma segura
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # postgres em base64
  POSTGRES_PASSWORD: YWRtaW4=  # admin em base64
