---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  DATABASE_URL: "postgresql://postgres:admin@postgres-service:5432/otel?schema=public"
  NODE_ENV: "production"
  HOST_GRPC: "api-otel-grpc:50051"